# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from LanguageSystem.DesktopRecording import DesktopRecording
from LanguageSystem.TranslationAI import TranslationAI
from LanguageSystem.PrimitiveTranscription import Transcription
from GUI.SubtitlesGUI import SubtitleWindow
from Threadpool import Threadpool 

from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import pathlib
import threading

class ControlWindow(QtWidgets.QMainWindow):
    def __init__(self, app : QtWidgets.QApplication, pool : Threadpool):
        super().__init__()
        
        self.originalLanguage = "ja-JP"
        self.finalLanguage = "en-US"

        self.pool = pool
        self.updateTranscriptEvent = threading.Event()
        self.transcriptList = []

        self.recording = DesktopRecording(pool)
        self.transcription = Transcription(pool, self.recording, self.originalLanguage)
        self.translation = TranslationAI(pool, self.transcription, self.originalLanguage, self.finalLanguage)

        self.app = app
        self.subtitles = SubtitleWindow(app)

        self.setupUi()

    def setupUi(self):
        self.setObjectName("ControlWindow")
        self.resize(700, 448)
        self.setMinimumSize(QtCore.QSize(700, 448))
        self.setMaximumSize(QtCore.QSize(700, 448))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(pathlib.Path(__file__).parent.parent.resolve()) + "/Resources/Logo.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.Line = QtWidgets.QFrame(self.centralwidget)
        self.Line.setGeometry(QtCore.QRect(350, -1, 20, 441))
        self.Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Line.setLineWidth(1)
        self.Line.setObjectName("Line")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(0, 50, 351, 381))
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -131, 334, 878))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")

        self.TranscriptLabel = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.TranscriptLabel.setFont(font)
        self.TranscriptLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.TranscriptLabel.setWordWrap(True)
        self.TranscriptLabel.setObjectName("TranscriptLabel")

        self.verticalLayout.addWidget(self.TranscriptLabel)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.StartButton = QtWidgets.QPushButton(self.centralwidget)
        self.StartButton.setGeometry(QtCore.QRect(450, 50, 161, 81))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.StartButton.setFont(font)
        self.StartButton.setObjectName("StartButton")
        self.StartButton.clicked.connect(self.onStartButtonClicked)

        self.NamingFrame = QtWidgets.QFrame(self.centralwidget)
        self.NamingFrame.setGeometry(QtCore.QRect(370, 160, 321, 61))
        self.NamingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NamingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NamingFrame.setObjectName("NamingFrame")

        self.NameInput = QtWidgets.QTextEdit(self.NamingFrame)
        self.NameInput.setGeometry(QtCore.QRect(20, 20, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameInput.setFont(font)
        self.NameInput.setObjectName("NameInput")

        self.NameLabel = QtWidgets.QLabel(self.NamingFrame)
        self.NameLabel.setGeometry(QtCore.QRect(90, 0, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.NameLabel.setFont(font)
        self.NameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NameLabel.setObjectName("NameLabel")

        self.SavingFrame = QtWidgets.QFrame(self.centralwidget)
        self.SavingFrame.setGeometry(QtCore.QRect(370, 210, 321, 71))
        self.SavingFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SavingFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SavingFrame.setObjectName("SavingFrame")

        self.SaveButton = QtWidgets.QPushButton(self.SavingFrame)
        self.SaveButton.setGeometry(QtCore.QRect(20, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")

        self.DeleteButton = QtWidgets.QPushButton(self.SavingFrame)
        self.DeleteButton.setGeometry(QtCore.QRect(171, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.DeleteButton.setFont(font)
        self.DeleteButton.setObjectName("DeleteButton")
        self.DeleteButton.clicked.connect(self.onDeleteButtonClicked)

        self.TranscriptTitle = QtWidgets.QLabel(self.centralwidget)
        self.TranscriptTitle.setGeometry(QtCore.QRect(0, 10, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.TranscriptTitle.setFont(font)
        self.TranscriptTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.TranscriptTitle.setObjectName("TranscriptTitle")

        self.NavigationFrame = QtWidgets.QFrame(self.centralwidget)
        self.NavigationFrame.setGeometry(QtCore.QRect(370, 300, 321, 121))
        self.NavigationFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.NavigationFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.NavigationFrame.setObjectName("NavigationFrame")

        self.SettingsButton = QtWidgets.QPushButton(self.NavigationFrame)
        self.SettingsButton.setGeometry(QtCore.QRect(30, 70, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setObjectName("SettingsButton")

        self.HelpButton = QtWidgets.QPushButton(self.NavigationFrame)
        self.HelpButton.setGeometry(QtCore.QRect(170, 70, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.HelpButton.setFont(font)
        self.HelpButton.setObjectName("HelpButton")

        self.TranscriptsButton = QtWidgets.QPushButton(self.NavigationFrame)
        self.TranscriptsButton.setGeometry(QtCore.QRect(100, 20, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.TranscriptsButton.setFont(font)
        self.TranscriptsButton.setObjectName("TranscriptsButton")

        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("ControlWindow", "MainWindow"))
        self.TranscriptLabel.setText(_translate("ControlWindow", ""))
        self.StartButton.setText(_translate("ControlWindow", "Start"))
        self.NameInput.setHtml(_translate("ControlWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.NameInput.setPlaceholderText(_translate("ControlWindow", "Transcript Name"))
        self.NameLabel.setText(_translate("ControlWindow", "Transcript Name"))
        self.SaveButton.setText(_translate("ControlWindow", "Save"))
        self.DeleteButton.setText(_translate("ControlWindow", "Delete"))
        self.TranscriptTitle.setText(_translate("ControlWindow", "Transcript"))
        self.SettingsButton.setText(_translate("ControlWindow", "Settings"))
        self.HelpButton.setText(_translate("ControlWindow", "Help"))
        self.TranscriptsButton.setText(_translate("ControlWindow", "Transcripts"))

    def updateTranscript(self):
        date = ""
        while not self.updateTranscriptEvent.is_set():
            translation = self.translation.getTranslation()

            if len(self.transcriptList):
                if translation == "..." and self.transcriptList[-1][1].split()[-1] == "...":
                    continue

            if not date == str(datetime.now().strftime("%d:%m:%y %H:%M")):
                date = str(datetime.now().strftime("%d:%m:%y %H:%M"))
                self.transcriptList.append([date, translation])
            else:
                self.transcriptList[-1][1] += " " + translation

            self.subtitles.setSubtitle(translation)
            self.TranscriptLabel.setText(self.generateText())

    def generateText(self):
        text = ""
        for i in self.transcriptList:
            text += "[" + str(i[0]) + "] "
            text += str(i[1])
            text += "\n"
        return text

    def checkPlaying(self):
        if self.StartButton.text() == "Stop":
            msg = QtWidgets.QMessageBox()
            msg.setIcon(QtWidgets.QMessageBox.Warning)
            msg.setText("You must stop your recording")
            msg.setWindowTitle("Warning")

            msg.setStandardButtons(QtWidgets.QMessageBox.Ok)
            msg.defaultButton = QtWidgets.QMessageBox.Ok

            msg.exec_()

            return True
        return False

    def onStartButtonClicked(self):
        if(self.StartButton.text() == "Start"):
            self.subtitles.clearSubtitles()
            self.StartButton.setText("Stop")

            self.recording.startRecording()
            self.transcription.startGeneration()
            self.translation.startTranslation()

            self.subtitles.show()
            self.subtitles.setSubtitle("")

            self.updateTranscriptEvent.clear()
            self.pool.submit(self.updateTranscript)
        else:
            self.StartButton.setText("Start")

            self.updateTranscriptEvent.set()
            self.pool.getResult(self.updateTranscript.__name__)

            self.subtitles.close()

            self.recording.stopRecording()
            self.transcription.stopGeneration()
            self.translation.stopTranslation()

    def onDeleteButtonClicked(self):
        if self.checkPlaying():
            return

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Warning)
        msg.setText("Are you sure you want to delete your transcript?")
        msg.setWindowTitle("Warning")

        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        msg.defaultButton = QtWidgets.QMessageBox.No

        msg.buttonClicked.connect(self.onDeleteWarningDecided)
        msg.exec_()
    
    def onDeleteWarningDecided(self, decision):
        if decision.text() == "&Yes":
            print("Hi")
            self.transcriptList = []
            self.subtitles.clearSubtitles()
            self.TranscriptLabel.setText("")