# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Help.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_self(QtWidgets.QMainWindow):
    def setupUi(self):
        self.setObjectName("HelpWindow")
        self.resize(700, 448)
        self.setMinimumSize(QtCore.QSize(700, 448))
        self.setMaximumSize(QtCore.QSize(700, 448))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.HelpLabel = QtWidgets.QLabel(self.centralwidget)
        self.HelpLabel.setGeometry(QtCore.QRect(280, 10, 141, 41))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.HelpLabel.setFont(font)
        self.HelpLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.HelpLabel.setObjectName("HelpLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 60, 681, 311))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 662, 718))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(270, 380, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Translation Transcriptor"))
        self.HelpLabel.setText(_translate("self", "Help"))
        self.label_2.setText(_translate("self", "Introduction:\n"
"The translation transcriptor translates audio in online meetings, presenting it as subtitles for easy viewing.\n"
"Translated transcripts are stored based on your account, viewable later via the search window.\n"
"\n"
"Control window:\n"
"Start/stop button - starts/stops recording the online meeting.\n"
"Transcript name text bar - input the transcript name for saving.\n"
"Save button - saves the transcript to your account.\n"
"Delete button - deletes the current transcript if not saved.\n"
"Transcript button - goes to the search window.\n"
"Help button - goes to the help window.\n"
"Settings button - goes to Settings.\n"
"\n"
"Transcript window:\n"
"Search bar - filters the output to find specific parts.\n"
"Search button - applies the filter.\n"
"Back button - returns to saved transcripts or the control panel.\n"
"Clicking a transcript shows the full transcript.\n"
"\n"
"Settings window:\n"
"Original Language - the language spoken in the audio.\n"
"Translated Language - the language for subtitles.\n"
"Recording Interval - the time each sentence segment is shown.\n"
"Max Lines - the maximum number of subtitle lines.\n"
"Font Size - the size of the subtitle letters.\n"
"Y Position - the height where subtitles are displayed."))
        self.BackButton.setText(_translate("self", "Back"))
