# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib

from UserSystem.UserDetailsStorage import UserDetailsStorage
from GUI.ControlGUI import ControlWindow

class LoginRegisterWindow(QtWidgets.QMainWindow):
    def __init__(self, app : QtWidgets.QApplication):
        super().__init__()
        self.setupUi()

        self.app = app
        self.storage : UserDetailsStorage = UserDetailsStorage()

    def setupUi(self):
        #Create the window
        self.setObjectName("LoginRegisterWindow")
        self.resize(560, 448)
        self.setMinimumSize(QtCore.QSize(560, 448))
        self.setMaximumSize(QtCore.QSize(560, 448))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(pathlib.Path(__file__).parent.parent.resolve()) + "/Resources/Logo.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        # The frame for the username input
        self.UsernameFrame = QtWidgets.QFrame(self.centralwidget)
        self.UsernameFrame.setGeometry(QtCore.QRect(10, 160, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.UsernameFrame.setFont(font)
        self.UsernameFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.UsernameFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.UsernameFrame.setObjectName("UsernameFrame")

        # The username input box
        self.UsernameInput = QtWidgets.QLineEdit(self.UsernameFrame)
        self.UsernameInput.setGeometry(QtCore.QRect(120, 10, 311, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.UsernameInput.setFont(font)
        self.UsernameInput.setAutoFillBackground(False)
        self.UsernameInput.setText("")
        self.UsernameInput.setObjectName("UsernameInput")

        # The label for the username input
        self.UsernameLabel = QtWidgets.QLabel(self.UsernameFrame)
        self.UsernameLabel.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.UsernameLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.UsernameLabel.setObjectName("UsernameLabel")

        # The frame for the password input
        self.PasswordFrame = QtWidgets.QFrame(self.centralwidget)
        self.PasswordFrame.setGeometry(QtCore.QRect(10, 230, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.PasswordFrame.setFont(font)
        self.PasswordFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.PasswordFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.PasswordFrame.setObjectName("PasswordFrame")

        # The password input box
        self.PasswordInput = QtWidgets.QLineEdit(self.PasswordFrame)
        self.PasswordInput.setGeometry(QtCore.QRect(120, 10, 311, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.PasswordInput.setFont(font)
        self.PasswordInput.setAutoFillBackground(False)
        self.PasswordInput.setText("")
        self.PasswordInput.setObjectName("PasswordInput")

        # The label for the password input
        self.PasswordLabel = QtWidgets.QLabel(self.PasswordFrame)
        self.PasswordLabel.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.PasswordLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.PasswordLabel.setObjectName("PasswordLabel")

        # The frame for the submit buttons
        self.SubmitButtons = QtWidgets.QFrame(self.centralwidget)
        self.SubmitButtons.setGeometry(QtCore.QRect(10, 300, 541, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.SubmitButtons.setFont(font)
        self.SubmitButtons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubmitButtons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubmitButtons.setObjectName("SubmitButtons")

        # The log in button
        self.LogInButton = QtWidgets.QPushButton(self.SubmitButtons)
        self.LogInButton.setGeometry(QtCore.QRect(90, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.LogInButton.setFont(font)
        self.LogInButton.setObjectName("LogInButton")
        self.LogInButton.clicked.connect(self.onLoginButtonClicked)

        # The register button
        self.RegisterButton = QtWidgets.QPushButton(self.SubmitButtons)
        self.RegisterButton.setGeometry(QtCore.QRect(290, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.RegisterButton.setFont(font)
        self.RegisterButton.setObjectName("RegisterButton")
        self.RegisterButton.clicked.connect(self.onRegisterButtonClicked)

        # The notice label
        self.NoticeLabel = QtWidgets.QLabel(self.SubmitButtons)
        self.NoticeLabel.setGeometry(QtCore.QRect(150, 10, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.NoticeLabel.setFont(font)
        self.NoticeLabel.setStyleSheet("color: red")
        self.NoticeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.NoticeLabel.setObjectName("NoticeLabel")

        # The logo label
        self.LogoLabel = QtWidgets.QLabel(self.centralwidget)
        self.LogoLabel.setGeometry(QtCore.QRect(200, 10, 151, 141))
        self.LogoLabel.setText("")
        self.LogoLabel.setPixmap(QtGui.QPixmap(str(pathlib.Path(__file__).parent.parent.resolve()) + "/Resources/Logo.jpeg"))
        self.LogoLabel.setScaledContents(True)
        self.LogoLabel.setObjectName("LogoLabel")

        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("LoginRegisterWindow", "Translation Transcriptor"))
        self.UsernameInput.setPlaceholderText(_translate("LoginRegisterWindow", "Username"))
        self.UsernameLabel.setText(_translate("LoginRegisterWindow", "Username"))
        self.PasswordInput.setPlaceholderText(_translate("LoginRegisterWindow", "Password"))
        self.PasswordLabel.setText(_translate("LoginRegisterWindow", "Password"))
        self.LogInButton.setText(_translate("LoginRegisterWindow", "Log-In"))
        self.RegisterButton.setText(_translate("LoginRegisterWindow", "Register"))
        self.NoticeLabel.setText(_translate("LoginRegisterWindow", ""))

    def onLoginButtonClicked(self):
        if self.storage.logIn(self.UsernameInput.text(), self.PasswordInput.text()):
            self.NoticeLabel.setText("Log in successful")

            self.controlWindow = ControlWindow(self.app)
            self.controlWindow.show()
            self.close()
        else:
            self.NoticeLabel.setText("Log in failed")

    def onRegisterButtonClicked(self):
        if not self.storage.checkUserExistence(self.UsernameInput.text()):
            self.storage.signUp(self.UsernameInput.text(), self.PasswordInput.text())
            self.NoticeLabel.setText("Sign up successful")

            self.controlWindow = ControlWindow(self.app)
            self.controlWindow.show()
            self.close()
        else:
            self.NoticeLabel.setText("Username already exists")