# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Searching.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UserSystem.EncryptionSystem import EncryptionSystem
from UserSystem.UserDetailsStorage import UserDetailsStorage

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from GUI.ManagerGUI import ManagerWindow


class SearchingWindow(QtWidgets.QMainWindow):
    def __init__(self, managerWindow : 'ManagerWindow'):
        super().__init__()

        self.managerWindow : 'ManagerWindow' = managerWindow

        self.userDetails : UserDetailsStorage = UserDetailsStorage()
        self.encryption : EncryptionSystem = EncryptionSystem()

        self.isSwitching = False

        self.setupUi()

    def setupUi(self):
        self.setObjectName("self")
        self.resize(700, 448)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.BackButton.clicked.connect(self.onBackButtonClicked)

        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(150, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchBar.setFont(font)
        self.SearchBar.setObjectName("SearchBar")

        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(560, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")

        self.TranscriptScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.TranscriptScroll.setEnabled(True)
        self.TranscriptScroll.setGeometry(QtCore.QRect(10, 70, 681, 371))
        self.TranscriptScroll.setWidgetResizable(True)
        self.TranscriptScroll.setObjectName("TranscriptScroll")
        self.TranscriptScroll.show()

        self.scrollAreaWidgetTranscript = QtWidgets.QWidget()
        self.scrollAreaWidgetTranscript.setGeometry(QtCore.QRect(0, 0, 679, 369))
        self.scrollAreaWidgetTranscript.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetTranscript.setObjectName("scrollAreaWidgetTranscript")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetTranscript)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TranscriptScroll.setWidget(self.scrollAreaWidgetTranscript)

        self.SectionScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.SectionScroll.setEnabled(True)
        self.SectionScroll.setGeometry(QtCore.QRect(10, 70, 681, 371))
        self.SectionScroll.setWidgetResizable(True)
        self.SectionScroll.setObjectName("SectionScroll")
        self.SectionScroll.hide()

        self.scrollAreaWidgetSection = QtWidgets.QWidget()
        self.scrollAreaWidgetSection.setGeometry(QtCore.QRect(0, -372, 662, 741))
        self.scrollAreaWidgetSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetSection.setObjectName("scrollAreaWidgetSection")

        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetSection)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.SectionLabel = QtWidgets.QLabel(self.scrollAreaWidgetSection)
        self.SectionLabel.setMinimumSize(QtCore.QSize(662, 0))
        self.SectionLabel.setMaximumSize(QtCore.QSize(662, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SectionLabel.setFont(font)
        self.SectionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SectionLabel.setWordWrap(True)
        self.SectionLabel.setObjectName("SectionLabel")

        self.verticalLayout_2.addWidget(self.SectionLabel)
        self.SectionScroll.setWidget(self.scrollAreaWidgetSection)
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Translation Transcriptor"))
        self.BackButton.setText(_translate("self", "Back"))
        self.SearchButton.setText(_translate("self", "Search"))
        self.SectionLabel.setText(_translate("self", "Test"))

    def closeEvent(self, event):
        if self.isSwitching:
            return

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Question)
        msg.setText("Are you sure you want to exit?")
        msg.setWindowTitle("Exit")
        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        result = msg.exec_()
        
        if result == QtWidgets.QMessageBox.No:
            event.ignore()
            return
        
        self.encryption.encrypt(self.userDetails.password, self.userDetails.accountPath)

    def onBackButtonClicked(self):
        if not self.TranscriptScroll.isHidden():
            self.isSwitching = True
            self.managerWindow.switchWindow("ControlWindow")