# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Searching.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UserSystem.EncryptionSystem import EncryptionSystem
from UserSystem.UserDetailsStorage import UserDetailsStorage

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from GUI.ManagerGUI import ManagerWindow

class SearchingWindow(QtWidgets.QMainWindow):
    # Setup the searching window
    def __init__(self, managerWindow : 'ManagerWindow'):
        super().__init__()

        # Store the manager window
        self.managerWindow : 'ManagerWindow' = managerWindow

        # Store the user details and encryption objects
        self.userDetails : UserDetailsStorage = UserDetailsStorage()
        self.encryption : EncryptionSystem = EncryptionSystem()

        # Used to prevent the window from closing when switching windows
        self.isSwitching = False

        # Setup the ui
        self.setupUi()

        # Store the transcript ID and transcript buttons
        self.transcriptionID = 0
        self.transcriptButtons = []

        # Generate the transcript buttons
        self.generateTranscriptButtons("")

    # Setup the ui
    def setupUi(self):
        # Create the main widgets
        self.setObjectName("self")
        self.resize(700, 448)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        # Create the back button
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.BackButton.clicked.connect(self.onBackButtonClicked)

        # Create the search bar
        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(150, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchBar.setFont(font)
        self.SearchBar.setObjectName("SearchBar")

        # Create the search button
        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(560, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchButton.clicked.connect(self.onSearchButtonClicked)

        # Create the transcript scroll area
        self.TranscriptScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.TranscriptScroll.setEnabled(True)
        self.TranscriptScroll.setGeometry(QtCore.QRect(10, 70, 681, 371))
        self.TranscriptScroll.setWidgetResizable(True)
        self.TranscriptScroll.setObjectName("TranscriptScroll")
        self.TranscriptScroll.show()

        # Create the transcript scroll area widget
        self.scrollAreaWidgetTranscript = QtWidgets.QWidget()
        self.scrollAreaWidgetTranscript.setGeometry(QtCore.QRect(0, 0, 679, 369))
        self.scrollAreaWidgetTranscript.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetTranscript.setObjectName("scrollAreaWidgetTranscript")

        # Create the transcript layout
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetTranscript)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.TranscriptScroll.setWidget(self.scrollAreaWidgetTranscript)

        # Create the section scroll area
        self.SectionScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.SectionScroll.setEnabled(True)
        self.SectionScroll.setGeometry(QtCore.QRect(10, 70, 681, 371))
        self.SectionScroll.setWidgetResizable(True)
        self.SectionScroll.setObjectName("SectionScroll")
        self.SectionScroll.hide()

        # Create the section scroll area widget
        self.scrollAreaWidgetSection = QtWidgets.QWidget()
        self.scrollAreaWidgetSection.setGeometry(QtCore.QRect(0, -372, 662, 741))
        self.scrollAreaWidgetSection.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetSection.setObjectName("scrollAreaWidgetSection")

        # Create the section layout
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetSection)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        # Create the section label
        self.SectionLabel = QtWidgets.QLabel(self.scrollAreaWidgetSection)
        self.SectionLabel.setMinimumSize(QtCore.QSize(662, 0))
        self.SectionLabel.setMaximumSize(QtCore.QSize(662, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SectionLabel.setFont(font)
        self.SectionLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.SectionLabel.setWordWrap(True)
        self.SectionLabel.setObjectName("SectionLabel")

        # Add the section label to the section layout
        self.verticalLayout_2.addWidget(self.SectionLabel)
        self.SectionScroll.setWidget(self.scrollAreaWidgetSection)

        # Set the main widget
        self.setCentralWidget(self.centralwidget)

        # Translate the ui
        self.retranslateUi()

        # Connect the slots
        QtCore.QMetaObject.connectSlotsByName(self)

    # Translate the ui
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("self", "Translation Transcriptor"))
        self.BackButton.setText(_translate("self", "Back"))
        self.SearchButton.setText(_translate("self", "Search"))
        self.SectionLabel.setText(_translate("self", "Test"))

    # Close the window
    def closeEvent(self, event):
        if self.isSwitching:
            return

        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Question)
        msg.setText("Are you sure you want to exit?")
        msg.setWindowTitle("Exit")
        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        result = msg.exec_()
        
        if result == QtWidgets.QMessageBox.No:
            event.ignore()
            return
        
        self.encryption.encrypt(self.userDetails.password, self.userDetails.accountPath)

    # Switch back to the control window
    def onBackButtonClicked(self):
        if not self.TranscriptScroll.isHidden():
            self.isSwitching = True
            self.managerWindow.switchWindow("ControlWindow")
        else:
            self.TranscriptScroll.show()
            self.SectionScroll.hide()

    # Generate the transcript buttons
    def generateTranscriptButtons(self, filter):
        # Remove the old buttons
        for button in self.transcriptButtons:
            button.close()
        self.transcriptButtons.clear()

        # Get the transcripts
        result = self.userDetails.getTranscripts(filter)

        # Add a button for each transcript
        for transcript in result:
            if self.verticalLayout.count() > 0 and isinstance(self.verticalLayout.itemAt(self.verticalLayout.count() - 1), QtWidgets.QSpacerItem):
                self.verticalLayout.takeAt(self.verticalLayout.count() - 1)

            button = QtWidgets.QPushButton(self.scrollAreaWidgetTranscript)
            button.setText(f"{transcript[1]} - {transcript[2]}")
            button.setFixedHeight(50)

            font = QtGui.QFont()
            font.setPointSize(12)
            button.setFont(font)

            self.verticalLayout.addWidget(button)

            spacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
            self.verticalLayout.addItem(spacer)

            button.clicked.connect(lambda _, transcriptID=transcript[0]: self.onTranscriptButtonClicked(transcriptID))
            self.transcriptButtons.append(button)

    # Switch to the transcript window
    def onTranscriptButtonClicked(self, transcriptID):
        self.TranscriptScroll.hide()
        self.SectionScroll.show()
        self.transcriptionID = transcriptID
        self.searchSection("")

    # Search the transcripts
    def onSearchButtonClicked(self):
        filter = self.SearchBar.text()
        self.generateTranscriptButtons(filter)
        self.searchSection(filter)
        
    # Search the sections
    def searchSection(self, filter):
        result = self.userDetails.getSections(self.transcriptionID, filter)
        body = ""
        for section in result:
            body += f"[{section[3]}] {section[2]} \n"

        self.SectionLabel.setText(body)
            
