# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(560, 448)
        SettingsWindow.setMinimumSize(QtCore.QSize(560, 448))
        SettingsWindow.setMaximumSize(QtCore.QSize(560, 448))
        self.centralwidget = QtWidgets.QWidget(SettingsWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")

        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(410, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")

        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(210, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")

        self.TranslationsFrame = QtWidgets.QFrame(self.centralwidget)
        self.TranslationsFrame.setGeometry(QtCore.QRect(10, 10, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranslationsFrame.setFont(font)
        self.TranslationsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TranslationsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TranslationsFrame.setObjectName("TranslationsFrame")

        self.OrigLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.OrigLanguageBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrigLanguageBox.setFont(font)
        self.OrigLanguageBox.setObjectName("OrigLanguageBox")
        self.OrigLanguageBox.addItem("")
        self.OrigLanguageBox.addItem("")

        self.TranLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.TranLanguageBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranLanguageBox.setFont(font)
        self.TranLanguageBox.setObjectName("TranLanguageBox")
        self.TranLanguageBox.addItem("")
        self.TranLanguageBox.addItem("")

        self.OrigLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.OrigLanguageLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.OrigLanguageLabel.setObjectName("OrigLanguageLabel")

        self.TranLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranLanguageLabel.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.TranLanguageLabel.setObjectName("TranLanguageLabel")

        self.TranslationsLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranslationsLabel.setGeometry(QtCore.QRect(0, 0, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TranslationsLabel.setFont(font)
        self.TranslationsLabel.setObjectName("TranslationsLabel")

        self.RecordingsFrame = QtWidgets.QFrame(self.centralwidget)
        self.RecordingsFrame.setGeometry(QtCore.QRect(10, 210, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingsFrame.setFont(font)
        self.RecordingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RecordingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RecordingsFrame.setObjectName("RecordingsFrame")

        self.RecordingInterBox = QtWidgets.QDoubleSpinBox(self.RecordingsFrame)
        self.RecordingInterBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingInterBox.setFont(font)
        self.RecordingInterBox.setMinimum(1.0)
        self.RecordingInterBox.setMaximum(60.0)
        self.RecordingInterBox.setObjectName("RecordingInterBox")

        self.RecordingInterLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingInterLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.RecordingInterLabel.setObjectName("RecordingInterLabel")

        self.RecordingsLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingsLabel.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecordingsLabel.setFont(font)
        self.RecordingsLabel.setObjectName("RecordingsLabel")

        self.SubtitlesFrame = QtWidgets.QFrame(self.centralwidget)
        self.SubtitlesFrame.setGeometry(QtCore.QRect(290, 10, 151, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SubtitlesFrame.setFont(font)
        self.SubtitlesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubtitlesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubtitlesFrame.setObjectName("SubtitlesFrame")

        self.MaxLinesBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.MaxLinesBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MaxLinesBox.setFont(font)
        self.MaxLinesBox.setMinimum(1)
        self.MaxLinesBox.setMaximum(10)
        self.MaxLinesBox.setObjectName("MaxLinesBox")

        self.FontSizeBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.FontSizeBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FontSizeBox.setFont(font)
        self.FontSizeBox.setMinimum(8)
        self.FontSizeBox.setMaximum(50)
        self.FontSizeBox.setObjectName("FontSizeBox")

        self.YPositionBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.YPositionBox.setGeometry(QtCore.QRect(10, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YPositionBox.setFont(font)
        self.YPositionBox.setMinimum(100)
        self.YPositionBox.setMaximum(10000)
        self.YPositionBox.setObjectName("YPositionBox")

        self.MaxLinesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.MaxLinesLabel.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.MaxLinesLabel.setObjectName("MaxLinesLabel")
        
        self.FontSizeLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.FontSizeLabel.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.FontSizeLabel.setObjectName("FontSizeLabel")

        self.YPositionLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.YPositionLabel.setGeometry(QtCore.QRect(10, 200, 71, 16))
        self.YPositionLabel.setObjectName("YPositionLabel")

        self.SubtitlesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.SubtitlesLabel.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SubtitlesLabel.setFont(font)
        self.SubtitlesLabel.setObjectName("SubtitlesLabel")

        self.Line = QtWidgets.QFrame(self.centralwidget)
        self.Line.setGeometry(QtCore.QRect(270, 0, 20, 371))
        self.Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Line.setLineWidth(1)
        self.Line.setObjectName("Line")
        
        SettingsWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingsWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Translation Transcriptor"))
        self.BackButton.setText(_translate("SettingsWindow", "Back"))
        self.ResetButton.setText(_translate("SettingsWindow", "Reset"))
        self.SaveButton.setText(_translate("SettingsWindow", "Save"))
        self.OrigLanguageBox.setItemText(0, _translate("SettingsWindow", "English"))
        self.OrigLanguageBox.setItemText(1, _translate("SettingsWindow", "Japanese"))
        self.TranLanguageBox.setItemText(0, _translate("SettingsWindow", "English"))
        self.TranLanguageBox.setItemText(1, _translate("SettingsWindow", "Japanese"))
        self.OrigLanguageLabel.setText(_translate("SettingsWindow", "Original Language"))
        self.TranLanguageLabel.setText(_translate("SettingsWindow", "Translated Language"))
        self.TranslationsLabel.setText(_translate("SettingsWindow", "Translations"))
        self.RecordingInterLabel.setText(_translate("SettingsWindow", "Recording Interval"))
        self.RecordingsLabel.setText(_translate("SettingsWindow", "Recordings"))
        self.MaxLinesLabel.setText(_translate("SettingsWindow", "Max Lines"))
        self.FontSizeLabel.setText(_translate("SettingsWindow", "Font Size"))
        self.YPositionLabel.setText(_translate("SettingsWindow", "Y Position"))
        self.SubtitlesLabel.setText(_translate("SettingsWindow", "Subtitles"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SettingsWindow = QtWidgets.QMainWindow()
    ui = Ui_SettingsWindow()
    ui.setupUi(SettingsWindow)
    SettingsWindow.show()
    sys.exit(app.exec_())
