# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib

from UserSystem.SettingsHandler import SettingsHandler
from UserSystem.UserDetailsStorage import UserDetailsStorage
from UserSystem.EncryptionSystem import EncryptionSystem

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from GUI.ManagerGUI import ManagerWindow

class SettingsWindow(QtWidgets.QMainWindow):
    # Constructor for the SettingsWindow class
    def __init__(self, managerWindow : 'ManagerWindow'):
        # Calls the superclass constructor
        super().__init__()

        # Stores the manager window
        self.managerWindow : 'ManagerWindow' = managerWindow
        # Used to prevent the window from closing when switching windows
        self.isSwitching = False

        # Gets the instance of SettingsHandler
        self.settingsHandler : SettingsHandler = SettingsHandler()

        # Gets the instance of UserDetailsStorage
        self.userDetails : UserDetailsStorage = UserDetailsStorage()
        # Gets the instance of EncryptionSystem
        self.encryption : EncryptionSystem = EncryptionSystem()


        # Sets up the ui
        self.setupUi()
    
    # Constructor for the SettingsWindow class
    def __init__(self, managerWindow : 'ManagerWindow'):
        # Calls the superclass constructor
        super().__init__()

        # Stores the manager window
        self.managerWindow : 'ManagerWindow' = managerWindow
        # Used to prevent the window from closing when switching windows
        self.isSwitching = False

        # Gets the instance of SettingsHandler
        self.settingsHandler : SettingsHandler = SettingsHandler()
        # Gets the instance of UserDetailsStorage
        self.userDetails : UserDetailsStorage = UserDetailsStorage()
        # Gets the instance of EncryptionSystem
        self.encryption : EncryptionSystem = EncryptionSystem()

        # Sets up the ui
        self.setupUi()

    # Sets up the UI for the window
    def setupUi(self):
        # Window properties
        self.setObjectName("SettingsWindow")
        self.resize(560, 448)
        self.setMinimumSize(QtCore.QSize(560, 448))
        self.setMaximumSize(QtCore.QSize(560, 448))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(pathlib.Path(__file__).parent.parent.resolve()) + "/Resources/Logo.jpeg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        # Back button
        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.BackButton.clicked.connect(self.onBackButtonClicked)

        # Reset button
        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(410, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.clicked.connect(self.onResetButtonClicked)

        # Save button
        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(210, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.SaveButton.clicked.connect(self.onSaveButtonClicked)

        # Translations frame
        self.TranslationsFrame = QtWidgets.QFrame(self.centralwidget)
        self.TranslationsFrame.setGeometry(QtCore.QRect(10, 10, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranslationsFrame.setFont(font)
        self.TranslationsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TranslationsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TranslationsFrame.setObjectName("TranslationsFrame")

        # Original language combo box
        self.OrigLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.OrigLanguageBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrigLanguageBox.setFont(font)
        self.OrigLanguageBox.setObjectName("OrigLanguageBox")
        self.OrigLanguageBox.addItems(sorted(self.settingsHandler.languageCodes.keys()))
        self.OrigLanguageBox.setCurrentText(self.settingsHandler.getSetting("OriginalLanguage"))

        # Translation language combo box
        self.TranLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.TranLanguageBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranLanguageBox.setFont(font)
        self.TranLanguageBox.setObjectName("TranLanguageBox")
        self.TranLanguageBox.addItems(sorted(self.settingsHandler.languageCodes.keys()))
        self.TranLanguageBox.setCurrentText(self.settingsHandler.getSetting("FinalLanguage"))

        # Original language label
        self.OrigLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.OrigLanguageLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.OrigLanguageLabel.setObjectName("OrigLanguageLabel")

        # Translation language label
        self.TranLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranLanguageLabel.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.TranLanguageLabel.setObjectName("TranLanguageLabel")

        # Translations label
        self.TranslationsLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranslationsLabel.setGeometry(QtCore.QRect(0, 0, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TranslationsLabel.setFont(font)
        self.TranslationsLabel.setObjectName("TranslationsLabel")

        # Recordings frame
        self.RecordingsFrame = QtWidgets.QFrame(self.centralwidget)
        self.RecordingsFrame.setGeometry(QtCore.QRect(10, 210, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingsFrame.setFont(font)
        self.RecordingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RecordingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RecordingsFrame.setObjectName("RecordingsFrame")

        # Recording interval box
        self.RecordingInterBox = QtWidgets.QDoubleSpinBox(self.RecordingsFrame)
        self.RecordingInterBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingInterBox.setFont(font)
        self.RecordingInterBox.setMinimum(1.0)
        self.RecordingInterBox.setMaximum(60.0)
        self.RecordingInterBox.setObjectName("RecordingInterBox")
        self.RecordingInterBox.setValue(float(self.settingsHandler.getSetting("RecordingInterval")))

        # Recording interval label
        self.RecordingInterLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingInterLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.RecordingInterLabel.setObjectName("RecordingInterLabel")

        # Recordings label
        self.RecordingsLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingsLabel.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecordingsLabel.setFont(font)
        self.RecordingsLabel.setObjectName("RecordingsLabel")

        # Subtitles frame
        self.SubtitlesFrame = QtWidgets.QFrame(self.centralwidget)
        self.SubtitlesFrame.setGeometry(QtCore.QRect(290, 10, 151, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SubtitlesFrame.setFont(font)
        self.SubtitlesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubtitlesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubtitlesFrame.setObjectName("SubtitlesFrame")

        # Maximum lines box
        self.MaxLinesBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.MaxLinesBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MaxLinesBox.setFont(font)
        self.MaxLinesBox.setMinimum(1)
        self.MaxLinesBox.setMaximum(10)
        self.MaxLinesBox.setObjectName("MaxLinesBox")
        self.MaxLinesBox.setValue(int(self.settingsHandler.getSetting("SubtitleLines")))

        # Font size box
        self.FontSizeBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.FontSizeBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FontSizeBox.setFont(font)
        self.FontSizeBox.setMinimum(8)
        self.FontSizeBox.setMaximum(50)
        self.FontSizeBox.setObjectName("FontSizeBox")
        self.FontSizeBox.setValue(int(self.settingsHandler.getSetting("SubtitleFontSize")))

        # Y position box
        self.YPositionBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.YPositionBox.setGeometry(QtCore.QRect(10, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YPositionBox.setFont(font)
        self.YPositionBox.setMinimum(100)
        self.YPositionBox.setMaximum(10000)
        self.YPositionBox.setObjectName("YPositionBox")
        self.YPositionBox.setValue(int(self.settingsHandler.getSetting("SubtitleWidth")))

        # Maximum lines label
        self.MaxLinesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.MaxLinesLabel.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.MaxLinesLabel.setObjectName("MaxLinesLabel")
        
        # Font size label
        self.FontSizeLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.FontSizeLabel.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.FontSizeLabel.setObjectName("FontSizeLabel")

        # Y position label
        self.YPositionLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.YPositionLabel.setGeometry(QtCore.QRect(10, 200, 71, 16))
        self.YPositionLabel.setObjectName("YPositionLabel")

        # Subtitles label
        self.SubtitlesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.SubtitlesLabel.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SubtitlesLabel.setFont(font)
        self.SubtitlesLabel.setObjectName("SubtitlesLabel")

        # Line
        self.Line = QtWidgets.QFrame(self.centralwidget)
        self.Line.setGeometry(QtCore.QRect(270, 0, 20, 371))
        self.Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Line.setLineWidth(1)
        self.Line.setObjectName("Line")
        
        self.setCentralWidget(self.centralwidget)

        # Translates ui
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    # Translates ui
    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("SettingsWindow", "Translation Transcriptor"))
        self.BackButton.setText(_translate("SettingsWindow", "Back"))
        self.ResetButton.setText(_translate("SettingsWindow", "Reset"))
        self.SaveButton.setText(_translate("SettingsWindow", "Save"))
        self.OrigLanguageLabel.setText(_translate("SettingsWindow", "Original Language"))
        self.TranLanguageLabel.setText(_translate("SettingsWindow", "Translated Language"))
        self.TranslationsLabel.setText(_translate("SettingsWindow", "Translations"))
        self.RecordingInterLabel.setText(_translate("SettingsWindow", "Recording Interval"))
        self.RecordingsLabel.setText(_translate("SettingsWindow", "Recordings"))
        self.MaxLinesLabel.setText(_translate("SettingsWindow", "Max Lines"))
        self.FontSizeLabel.setText(_translate("SettingsWindow", "Font Size"))
        self.YPositionLabel.setText(_translate("SettingsWindow", "Y Position"))
        self.SubtitlesLabel.setText(_translate("SettingsWindow", "Subtitles"))

    # CloseEvent is called when the window is about to be closed
    def closeEvent(self, event):
        # Check if the user is switching windows
        if self.isSwitching:
            return

        # Ask the user if they are sure they want to exit
        response = self.setQuestionBox("Are you sure you want to exit?", "Warning")
        # If the user clicked no, ignore the event
        if response == QtWidgets.QMessageBox.No:
            event.ignore()
            return
        
        # Encrypt the user details
        self.encryption.encrypt(self.userDetails.password, self.userDetails.accountPath)

    # Asks the user a question and returns the result
    def setQuestionBox(self, text, title):
        # Create the message box
        msg = QtWidgets.QMessageBox()
        # Set the icon, text, and title
        msg.setIcon(QtWidgets.QMessageBox.Question)
        msg.setText(text)
        msg.setWindowTitle(title)

        # Set the standard buttons
        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        # Set the default button
        msg.defaultButton = QtWidgets.QMessageBox.No

        # Execute the message box and return the result
        return msg.exec_()
    
    # Switches back to the control window when the back button is clicked
    def onBackButtonClicked(self):
        # Switches the window to the control window
        self.isSwitching = True
        self.managerWindow.switchWindow("ControlWindow")

    # Handles reset button clicks
    def onResetButtonClicked(self):
        # Confirm reset
        response = self.setQuestionBox("Are you sure you want to reset all settings?", "Reset Settings")
        if response == QtWidgets.QMessageBox.No:
            return
        
        # Reset original language
        self.OrigLanguageBox.setCurrentText(self.settingsHandler.getSetting("OriginalLanguage"))
        # Reset translated language
        self.TranLanguageBox.setCurrentText(self.settingsHandler.getSetting("FinalLanguage"))

        # Reset recording interval
        self.RecordingInterBox.setValue(int(self.settingsHandler.getSetting("RecordingInterval")))
        # Reset subtitle lines
        self.MaxLinesBox.setValue(int(self.settingsHandler.getSetting("SubtitleLines")))
        # Reset font size
        self.FontSizeBox.setValue(int(self.settingsHandler.getSetting("SubtitleFontSize")))
        # Reset subtitle width
        self.YPositionBox.setValue(int(self.settingsHandler.getSetting("SubtitleWidth")))

# Save the settings when the save button is clicked
def onSaveButtonClicked(self):
    # Check if the user is sure they want to save the settings
    response = self.setQuestionBox("Are you sure you want to save all settings?", "Save Settings")
    if response == QtWidgets.QMessageBox.No:
        return

    # Save the original language
    self.settingsHandler.setSetting("OriginalLanguage", self.OrigLanguageBox.currentText())
    # Save the translated language
    self.settingsHandler.setSetting("FinalLanguage", self.TranLanguageBox.currentText())
    # Save the recording interval
    self.settingsHandler.setSetting("RecordingInterval", self.RecordingInterBox.value())
    # Save the subtitle lines
    self.settingsHandler.setSetting("SubtitleLines", self.MaxLinesBox.value())
    # Save the font size
    self.settingsHandler.setSetting("SubtitleFontSize", self.FontSizeBox.value())
    # Save the subtitle width
    self.settingsHandler.setSetting("SubtitleWidth", self.YPositionBox.value())
