# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from UserSystem.SettingsHandler import SettingsHandler
from UserSystem.UserDetailsStorage import UserDetailsStorage
from UserSystem.EncryptionSystem import EncryptionSystem

from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from GUI.ManagerGUI import ManagerWindow

class SettingsWindow(QtWidgets.QMainWindow):
    languageDict = {"en-US" : "English",
                    "ja-JP" : "Japanese",
                    "es-ES" : "Spanish",
                    "fr-FR" : "French",
                    "de-DE" : "German",
                    "it-IT" : "Italian",
                    "ru-RU" : "Russian",
                    "zh-CN" : "Chinese",
                    "tl-PH" : "Filipino"
                    }

    def __init__(self, managerWindow : 'ManagerWindow'):
        super().__init__()

        self.managerWindow : 'ManagerWindow' = managerWindow
        self.isSwitching = False

        self.settingsHandler : SettingsHandler = SettingsHandler()

        self.userDetails : UserDetailsStorage = UserDetailsStorage()
        self.encryption : EncryptionSystem = EncryptionSystem()


        self.setupUi()
    
    def setupUi(self):
        self.setObjectName("SettingsWindow")
        self.resize(560, 448)
        self.setMinimumSize(QtCore.QSize(560, 448))
        self.setMaximumSize(QtCore.QSize(560, 448))
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")

        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")
        self.BackButton.clicked.connect(self.onBackButtonClicked)

        self.ResetButton = QtWidgets.QPushButton(self.centralwidget)
        self.ResetButton.setGeometry(QtCore.QRect(410, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.ResetButton.setFont(font)
        self.ResetButton.setObjectName("ResetButton")
        self.ResetButton.clicked.connect(self.onResetButtonClicked)

        self.SaveButton = QtWidgets.QPushButton(self.centralwidget)
        self.SaveButton.setGeometry(QtCore.QRect(210, 380, 141, 61))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SaveButton.setFont(font)
        self.SaveButton.setObjectName("SaveButton")
        self.SaveButton.clicked.connect(self.onSaveButtonClicked)

        self.TranslationsFrame = QtWidgets.QFrame(self.centralwidget)
        self.TranslationsFrame.setGeometry(QtCore.QRect(10, 10, 191, 181))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranslationsFrame.setFont(font)
        self.TranslationsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TranslationsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TranslationsFrame.setObjectName("TranslationsFrame")

        self.OrigLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.OrigLanguageBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OrigLanguageBox.setFont(font)
        self.OrigLanguageBox.setObjectName("OrigLanguageBox")
        self.OrigLanguageBox.addItems(SettingsWindow.languageDict.values())
        self.OrigLanguageBox.setCurrentText(SettingsWindow.languageDict[self.settingsHandler.getSetting("OriginalLanguage")])

        self.TranLanguageBox = QtWidgets.QComboBox(self.TranslationsFrame)
        self.TranLanguageBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.TranLanguageBox.setFont(font)
        self.TranLanguageBox.setObjectName("TranLanguageBox")
        self.TranLanguageBox.addItems(SettingsWindow.languageDict.values())
        self.TranLanguageBox.setCurrentText(SettingsWindow.languageDict[self.settingsHandler.getSetting("FinalLanguage")])

        self.OrigLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.OrigLanguageLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.OrigLanguageLabel.setObjectName("OrigLanguageLabel")

        self.TranLanguageLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranLanguageLabel.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.TranLanguageLabel.setObjectName("TranLanguageLabel")

        self.TranslationsLabel = QtWidgets.QLabel(self.TranslationsFrame)
        self.TranslationsLabel.setGeometry(QtCore.QRect(0, 0, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.TranslationsLabel.setFont(font)
        self.TranslationsLabel.setObjectName("TranslationsLabel")

        self.RecordingsFrame = QtWidgets.QFrame(self.centralwidget)
        self.RecordingsFrame.setGeometry(QtCore.QRect(10, 210, 191, 91))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingsFrame.setFont(font)
        self.RecordingsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.RecordingsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.RecordingsFrame.setObjectName("RecordingsFrame")

        self.RecordingInterBox = QtWidgets.QDoubleSpinBox(self.RecordingsFrame)
        self.RecordingInterBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.RecordingInterBox.setFont(font)
        self.RecordingInterBox.setMinimum(1.0)
        self.RecordingInterBox.setMaximum(60.0)
        self.RecordingInterBox.setObjectName("RecordingInterBox")
        self.RecordingInterBox.setValue(float(self.settingsHandler.getSetting("RecordingInterval")))

        self.RecordingInterLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingInterLabel.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.RecordingInterLabel.setObjectName("RecordingInterLabel")

        self.RecordingsLabel = QtWidgets.QLabel(self.RecordingsFrame)
        self.RecordingsLabel.setGeometry(QtCore.QRect(0, 0, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.RecordingsLabel.setFont(font)
        self.RecordingsLabel.setObjectName("RecordingsLabel")

        self.SubtitlesFrame = QtWidgets.QFrame(self.centralwidget)
        self.SubtitlesFrame.setGeometry(QtCore.QRect(290, 10, 151, 271))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.SubtitlesFrame.setFont(font)
        self.SubtitlesFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.SubtitlesFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.SubtitlesFrame.setObjectName("SubtitlesFrame")

        self.MaxLinesBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.MaxLinesBox.setGeometry(QtCore.QRect(10, 40, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.MaxLinesBox.setFont(font)
        self.MaxLinesBox.setMinimum(1)
        self.MaxLinesBox.setMaximum(10)
        self.MaxLinesBox.setObjectName("MaxLinesBox")
        self.MaxLinesBox.setValue(int(self.settingsHandler.getSetting("SubtitleLines")))

        self.FontSizeBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.FontSizeBox.setGeometry(QtCore.QRect(10, 130, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FontSizeBox.setFont(font)
        self.FontSizeBox.setMinimum(8)
        self.FontSizeBox.setMaximum(50)
        self.FontSizeBox.setObjectName("FontSizeBox")
        self.FontSizeBox.setValue(int(self.settingsHandler.getSetting("SubtitleFontSize")))

        self.YPositionBox = QtWidgets.QSpinBox(self.SubtitlesFrame)
        self.YPositionBox.setGeometry(QtCore.QRect(10, 220, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.YPositionBox.setFont(font)
        self.YPositionBox.setMinimum(100)
        self.YPositionBox.setMaximum(10000)
        self.YPositionBox.setObjectName("YPositionBox")
        self.YPositionBox.setValue(int(self.settingsHandler.getSetting("SubtitleWidth")))

        self.MaxLinesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.MaxLinesLabel.setGeometry(QtCore.QRect(10, 20, 71, 21))
        self.MaxLinesLabel.setObjectName("MaxLinesLabel")
        
        self.FontSizeLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.FontSizeLabel.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.FontSizeLabel.setObjectName("FontSizeLabel")

        self.YPositionLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.YPositionLabel.setGeometry(QtCore.QRect(10, 200, 71, 16))
        self.YPositionLabel.setObjectName("YPositionLabel")

        self.SubtitlesLabel = QtWidgets.QLabel(self.SubtitlesFrame)
        self.SubtitlesLabel.setGeometry(QtCore.QRect(0, 0, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.SubtitlesLabel.setFont(font)
        self.SubtitlesLabel.setObjectName("SubtitlesLabel")

        self.Line = QtWidgets.QFrame(self.centralwidget)
        self.Line.setGeometry(QtCore.QRect(270, 0, 20, 371))
        self.Line.setFrameShape(QtWidgets.QFrame.VLine)
        self.Line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Line.setLineWidth(1)
        self.Line.setObjectName("Line")
        
        self.setCentralWidget(self.centralwidget)

        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("SettingsWindow", "Translation Transcriptor"))
        self.BackButton.setText(_translate("SettingsWindow", "Back"))
        self.ResetButton.setText(_translate("SettingsWindow", "Reset"))
        self.SaveButton.setText(_translate("SettingsWindow", "Save"))
        self.OrigLanguageLabel.setText(_translate("SettingsWindow", "Original Language"))
        self.TranLanguageLabel.setText(_translate("SettingsWindow", "Translated Language"))
        self.TranslationsLabel.setText(_translate("SettingsWindow", "Translations"))
        self.RecordingInterLabel.setText(_translate("SettingsWindow", "Recording Interval"))
        self.RecordingsLabel.setText(_translate("SettingsWindow", "Recordings"))
        self.MaxLinesLabel.setText(_translate("SettingsWindow", "Max Lines"))
        self.FontSizeLabel.setText(_translate("SettingsWindow", "Font Size"))
        self.YPositionLabel.setText(_translate("SettingsWindow", "Y Position"))
        self.SubtitlesLabel.setText(_translate("SettingsWindow", "Subtitles"))

    def closeEvent(self, event):
        if self.isSwitching:
            return

        response = self.setQuestionBox("Are you sure you want to exit?", "Warning")
        if response == QtWidgets.QMessageBox.No:
            event.ignore()
            return
        
        self.encryption.encrypt(self.userDetails.password, self.userDetails.accountPath)

    def setQuestionBox(self, text, title):
        msg = QtWidgets.QMessageBox()
        msg.setIcon(QtWidgets.QMessageBox.Question)
        msg.setText(text)
        msg.setWindowTitle(title)

        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No)
        msg.defaultButton = QtWidgets.QMessageBox.No

        return msg.exec_()
    
    def onBackButtonClicked(self):
        self.isSwitching = True
        self.managerWindow.switchWindow("ControlWindow")

    def onResetButtonClicked(self):
        response = self.setQuestionBox("Are you sure you want to reset all settings?", "Reset Settings")
        if response == QtWidgets.QMessageBox.No:
            return
        
        self.OrigLanguageBox.setCurrentText(self.settingsHandler.getSetting("OriginalLanguage"))
        self.TranLanguageBox.setCurrentText(self.settingsHandler.getSetting("FinalLanguage"))
        self.RecordingInterBox.setValue(int(self.settingsHandler.getSetting("RecordingInterval")))
        self.MaxLinesBox.setValue(int(self.settingsHandler.getSetting("SubtitleLines")))
        self.FontSizeBox.setValue(int(self.settingsHandler.getSetting("SubtitleFontSize")))
        self.YPositionBox.setValue(int(self.settingsHandler.getSetting("SubtitleWidth")))

    def onSaveButtonClicked(self):
        response = self.setQuestionBox("Are you sure you want to save all settings?", "Save Settings")
        if response == QtWidgets.QMessageBox.No:
            return
        
        self.settingsHandler.setSetting("OriginalLanguage", self.OrigLanguageBox.currentText())
        self.settingsHandler.setSetting("FinalLanguage", self.TranLanguageBox.currentText())
        self.settingsHandler.setSetting("RecordingInterval", self.RecordingInterBox.value())
        self.settingsHandler.setSetting("SubtitleLines", self.MaxLinesBox.value())
        self.settingsHandler.setSetting("SubtitleFontSize", self.FontSizeBox.value())
        self.settingsHandler.setSetting("SubtitleWidth", self.YPositionBox.value())