# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginRegister.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pathlib

class Ui_LoginRegisterWindow(object):
    def setupUi(self, login_register_window):
        # Create the window
        login_register_window.setObjectName("login_register_window")
        login_register_window.resize(560, 448)
        login_register_window.setStyleSheet("")
        self.central_widget = QtWidgets.QWidget(login_register_window)
        self.central_widget.setObjectName("central_widget")

        # Create the username frame and input box
        self.username_frame = QtWidgets.QFrame(self.central_widget)
        self.username_frame.setGeometry(QtCore.QRect(10, 160, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.username_frame.setFont(font)
        self.username_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.username_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.username_frame.setObjectName("username_frame")

        self.username_input = QtWidgets.QLineEdit(self.username_frame)
        self.username_input.setGeometry(QtCore.QRect(120, 10, 311, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.username_input.setFont(font)
        self.username_input.setAutoFillBackground(False)
        self.username_input.setText("")
        self.username_input.setObjectName("username_input")

        self.username_label = QtWidgets.QLabel(self.username_frame)
        self.username_label.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.username_label.setAlignment(QtCore.Qt.AlignCenter)
        self.username_label.setObjectName("username_label")

        # Create the password frame and input box
        self.password_frame = QtWidgets.QFrame(self.central_widget)
        self.password_frame.setGeometry(QtCore.QRect(10, 230, 541, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password_frame.setFont(font)
        self.password_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.password_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.password_frame.setObjectName("password_frame")

        self.password_input = QtWidgets.QLineEdit(self.password_frame)
        self.password_input.setGeometry(QtCore.QRect(120, 10, 311, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.password_input.setFont(font)
        self.password_input.setAutoFillBackground(False)
        self.password_input.setText("")
        self.password_input.setObjectName("password_input")

        self.password_label = QtWidgets.QLabel(self.password_frame)
        self.password_label.setGeometry(QtCore.QRect(0, 20, 121, 31))
        self.password_label.setAlignment(QtCore.Qt.AlignCenter)
        self.password_label.setObjectName("password_label")

        # Create the submit buttons frame
        self.submit_buttons = QtWidgets.QFrame(self.central_widget)
        self.submit_buttons.setGeometry(QtCore.QRect(10, 300, 541, 111))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.submit_buttons.setFont(font)
        self.submit_buttons.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.submit_buttons.setFrameShadow(QtWidgets.QFrame.Raised)
        self.submit_buttons.setObjectName("submit_buttons")

        # Create the login button
        self.login_button = QtWidgets.QPushButton(self.submit_buttons)
        self.login_button.setGeometry(QtCore.QRect(90, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")

        # Create the register button
        self.register_button = QtWidgets.QPushButton(self.submit_buttons)
        self.register_button.setGeometry(QtCore.QRect(290, 40, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.register_button.setFont(font)
        self.register_button.setObjectName("register_button")

        # Create the error label
        self.error_label = QtWidgets.QLabel(self.submit_buttons)
        self.error_label.setGeometry(QtCore.QRect(150, 10, 221, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: red")
        self.error_label.setAlignment(QtCore.Qt.AlignCenter)
        self.error_label.setObjectName("error_label")

        # Create the logo label
        self.logo_label = QtWidgets.QLabel(self.central_widget)
        self.logo_label.setGeometry(QtCore.QRect(200, 10, 151, 141))
        self.logo_label.setText("")
        self.logo_label.setPixmap(QtGui.QPixmap(str(pathlib.Path(__file__).parent.parent.resolve()) + "\Resources\Logo.jpeg"))
        self.logo_label.setScaledContents(True)
        self.logo_label.setObjectName("logo_label")

        login_register_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(login_register_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 560, 21))
        self.menubar.setObjectName("menubar")
        login_register_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(login_register_window)
        self.statusbar.setObjectName("statusbar")
        login_register_window.setStatusBar(self.statusbar)

        self.retranslateUi(login_register_window)
        QtCore.QMetaObject.connectSlotsByName(login_register_window)

    def retranslateUi(self, LoginRegisterWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginRegisterWindow.setWindowTitle(_translate("LoginRegisterWindow", "Translation Transcriptor"))
        self.username_input.setPlaceholderText(_translate("LoginRegisterWindow", "Username"))
        self.username_label.setText(_translate("LoginRegisterWindow", "Username"))
        self.password_input.setPlaceholderText(_translate("LoginRegisterWindow", "Password"))
        self.password_label.setText(_translate("LoginRegisterWindow", "Password"))
        self.login_button.setText(_translate("LoginRegisterWindow", "Log-In"))
        self.register_button.setText(_translate("LoginRegisterWindow", "Register"))
        self.error_label.setText(_translate("LoginRegisterWindow", "Something bad bad happened"))


import sys
app = QtWidgets.QApplication(sys.argv)
LoginRegisterWindow = QtWidgets.QMainWindow()
ui = Ui_LoginRegisterWindow()
ui.setupUi(LoginRegisterWindow)
LoginRegisterWindow.show()
sys.exit(app.exec_())
