# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Searching.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys


class Ui_SearchingWindow(QtWidgets.QMainWindow):
    def setupUi(self, SearchingWindow : QtWidgets.QMainWindow):
        SearchingWindow.setObjectName("SearchingWindow")
        SearchingWindow.resize(700, 448)
        self.centralwidget = QtWidgets.QWidget(SearchingWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.BackButton = QtWidgets.QPushButton(self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.BackButton.setFont(font)
        self.BackButton.setObjectName("BackButton")

        self.SearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.SearchBar.setGeometry(QtCore.QRect(150, 10, 411, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchBar.setFont(font)
        self.SearchBar.setObjectName("SearchBar")

        self.SearchButton = QtWidgets.QPushButton(self.centralwidget)
        self.SearchButton.setGeometry(QtCore.QRect(560, 10, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.SearchButton.setFont(font)
        self.SearchButton.setObjectName("SearchButton")
        self.SearchButton.clicked.connect(self.addButton)

        self.TranscriptScroll = QtWidgets.QScrollArea(self.centralwidget)
        self.TranscriptScroll.setEnabled(True)
        self.TranscriptScroll.setGeometry(QtCore.QRect(10, 70, 681, 371))
        self.TranscriptScroll.setWidgetResizable(True)
        self.TranscriptScroll.setObjectName("TranscriptScroll")

        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 679, 369))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")

        self.TranscriptScroll.setWidget(self.scrollAreaWidgetContents)
        SearchingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SearchingWindow)
        QtCore.QMetaObject.connectSlotsByName(SearchingWindow)

    def retranslateUi(self, SearchingWindow):
        _translate = QtCore.QCoreApplication.translate
        SearchingWindow.setWindowTitle(_translate("SearchingWindow", "Translation Transcriptor"))
        self.BackButton.setText(_translate("SearchingWindow", "Back"))
        self.SearchButton.setText(_translate("SearchingWindow", "Search"))

    def addButton(self):
        # Remove existing spacer if present
        if self.verticalLayout.count() > 0 and isinstance(self.verticalLayout.itemAt(self.verticalLayout.count() - 1), QtWidgets.QSpacerItem):
            self.verticalLayout.takeAt(self.verticalLayout.count() - 1)

        # Create a new button with a fixed size
        button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        button.setText("Button")
        button.setFixedHeight(50)

        # Add the button to the layout with no spacing
        self.verticalLayout.addWidget(button)

        # Add a spacer to push the buttons to the top
        spacer = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacer)



app = QtWidgets.QApplication(sys.argv)
mainWindow = Ui_SearchingWindow()
mainWindow.setupUi(mainWindow)
mainWindow.show()
sys.exit(app.exec_())
